### ISSUE TITLE
database file

### ISSUE THREAD

**Issue by MAGICCC** [rankenstein/docker-dudel#1]
Hi,

Somehow I cant link my database to my hostsystem...
I added ```/data/persistent/dudel/dudel.db:/dudel/dudel.db``` to my docker-compose.yml and edited the config.py to ```sqlite:////dudel/dudel.db```

Is there something I am missing?

**Comment by cdauth** [comment]
I don’t know, I only just created this image and haven’t used it a lot yet. In my tests, I used a Postgres database.

Can you post the log output of the container? Maybe there is some information written there. Also, I believe that the database file has to belong to the UID and PID 2.

**Comment by MAGICCC** [comment]
Well it only creates a folder instead a file on my host filesystem

**Comment by cdauth** [comment]
Ah, in that case you have to create the file first. Just creating an empty file (`touch /data/persistent/dudel/dudel.db && chown 2:2 /data/persistent/dudel/dudel.db`) should hopefully do the trick.

**Comment by cdauth** [comment]
The other way would be to use a folder as a volume, for example `/data/persistent/dudel:/data` and then configure `/data/dudel.db` as the database, then it should be created automatically.

**Comment by MAGICCC** [comment]
Hm
Edited the compose file to this:
```
version: '2'
services:
    dudel:
        container_name: dudel
        image: rankenstein/dudel
        volumes:
            - /data/persistent/asaf-doodle:/dudel
        ports:
            - 3645:8888
        restart: unless-stopped
```

Now when I want to start the container it jumps to some weird path I guess and cant find the python file:
```
dudel    | python2: can't open file 'manage.py': [Errno 2] No such file or directory
dudel exited with code 2
```
